name: PR Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate_PR_title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        id: validate_title
        shell: /usr/bin/bash -e {0}
        run: |
          # Check if the PR title contains one of the specified JIRA keys followed by a number
          if echo "${{ github.event.pull_request.title }}" | grep -qEi '^(PSREVCD|PSREVE|PSREDS|PSREADSYS|PSRE)-[0-9]+'; then
            echo "valid=true" >> $GITHUB_ENV
          else
            echo "valid=false" >> $GITHUB_ENV
            echo "PR title does not contain a valid JIRA key (PSREVCD, PSREVE, PSREDS, PSREADSYS, PSRE) followed by a number."

  warn_invalid_title:
    runs-on: ubuntu-latest
    needs: validate_PR_title
    if: env.valid == 'false'
    steps:
      - name: Warn about invalid PR title
        run: |
          echo "::warning title=Invalid PR Title::PR title does not contain a valid JIRA key (PSREVCD, PSREVE, PSREDS, PSREADSYS, PSRE) followed by a number. Please include a valid key and number in the title."
