name: PR Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate_PR_title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        id: validate_title
        run: |
          # Check if the PR title contains one of the specified JIRA keys followed by a number
          if ! echo "${{ github.event.pull_request.title }}" | grep -qEi '^(PSREVCD|PSREVE|PSREDS|PSREADSYS|PSRE)-[0-9]+'; then
            echo "PR title does not contain a valid JIRA key (PSREVCD, PSREVE, PSREDS, PSREADSYS, PSRE) followed by a number."
            echo "::set-output name=valid::false"
          else
            echo "::set-output name=valid::true"

  warn_invalid_title:
    runs-on: ubuntu-latest
    needs: validate_PR_title
    if: needs.validate_PR_title.outputs.valid == 'false'
    steps:
      - name: Warn about invalid PR title
        run: |
          echo "::warning title=Invalid PR Title::PR title does not contain a valid JIRA key (PSREVCD, PSREVE, PSREDS, PSREADSYS, PSRE) followed by a number. Please include a valid key and number in the title."
