name: PR Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate_PR_title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        run: |
          # Check if the PR title contains one of the specified JIRA keys followed by a number
          if ! echo "${{ github.event.pull_request.title }}" | grep -qEi '^(PSREVCD|PSREVE|PSREDS|PSREADSYS|PSRE)-[0-9]+'; then
            echo "PR title does not contain a valid JIRA key (PSREVCD, PSREVE, PSREDS, PSREADSYS, PSRE) followed by a number. Please include a valid key and number in the title."
            exit 1
          fi
